name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ghcr.io/harpertoken/ml-api:latest

    - name: Run E2E tests
      run: |
        # Start the container
        docker run -d --name ml-api-test -p 8000:8000 ghcr.io/harpertoken/ml-api:latest
        # Wait for startup
        sleep 30
        # Test health endpoint
        curl -f http://localhost:8000/health
        # Test models endpoint
        curl -f http://localhost:8000/models
        # Test status endpoint
        curl -f http://localhost:8000/status
        # Test chat endpoint
        curl -f -X POST http://localhost:8000/chat -H "Content-Type: application/json" -d '{"prompt": "Hello"}'
        # Clean up
        docker stop ml-api-test
        docker rm ml-api-test